PKCE implementation
micronaut-projects/micronaut-security pull request #1082
Opened 2022-08-23 09:43 UTC by n0tl3ss

TBA

2022-09-01 11:07 UTC, graemerocher commented
@strmik Can you review this PR to see if it fits your needs?

2022-09-05 14:22 UTC, strmik commented
@graemerocher LGTM! 

I am convinced that this exactly fits our needs and will work with our integration with implementation defaults.

Thanks a lot!

2022-11-15 10:26 UTC, graemerocher requested changes

2022-11-15 10:26 UTC, graemerocher commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/request/AuthorizationRequest.java
> +    Optional<PKCE> getPKCE(MutableHttpResponse response);
add the generic parameter `?` to the response here

2022-11-15 10:26 UTC, graemerocher commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/context/OauthCodeTokenRequestContext.java
> +    public String getPKCECodeVerifier() {
add nullability annotation and `@since`

2022-11-15 10:26 UTC, graemerocher commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/context/OpenIdCodeTokenRequestContext.java
> +    public String getPKCECodeVerifier() {
add nullability annotation and `@since`

2022-11-15 10:26 UTC, graemerocher commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/grants/AuthorizationCodeGrant.java
> +    public String getCodeVerifier() {
add nullability annotation and `@since`

2022-11-15 10:26 UTC, graemerocher commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/grants/AuthorizationCodeGrant.java
> +    public void setCodeVerifier(String codeVerifier) {
add nullability annotation and `@since`

2022-11-15 11:20 UTC, graemerocher approved these changes

2022-11-18 08:50 UTC, sdelamo requested changes
I have created a PR which addresses some of the feedback https://github.com/micronaut-projects/micronaut-security/pull/1144

2022-11-18 08:50 UTC, sdelamo commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/DefaultOauthAuthorizationResponseHandler.java
> +                                             @Nullable PKCEPersistence pkcePersistence) {
this is a breaking change

2022-11-18 08:50 UTC, sdelamo commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/context/OauthCodeTokenRequestContext.java
> +                                        @Nullable String codeVerify) {
this is a breaking change

2022-11-18 08:50 UTC, sdelamo commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/context/OpenIdCodeTokenRequestContext.java
> +                                         @Nullable String codeVerify) {
this is a breaking change. we should have another constructor.

2022-11-18 08:50 UTC, sdelamo commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/pkce/persistence/PKCEPersistence.java
> +    void persistPKCE(HttpRequest<?> request, MutableHttpResponse<?> response, PKCE pkce);
add Nullability annotation for method parameters

2022-11-18 08:50 UTC, sdelamo commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/request/AuthorizationRequest.java
> +    Optional<PKCE> getPKCE(MutableHttpResponse<?> response);
this should be a `default`  method returning `Optional.empty`

2022-11-18 08:50 UTC, sdelamo commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/request/DefaultOauthAuthorizationRequest.java
> +                                     @Nullable PKCEFactory pkceFactory) {
this is a breaking change. we should keep the old constructor.

2022-11-18 08:50 UTC, sdelamo commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/pkce/persistence/session/SessionPKCEPersistence.java
> +public class SessionPKCEPersistence implements PKCEPersistence {
we miss a functional test for this persistence method.

2022-11-18 08:55 UTC, graemerocher commented
@sdelamo do you want @n0tl3ss to address these comments or are you addressing them in other PR?

2022-11-18 10:35 UTC, sdelamo commented
closed via https://micronaut-projects.github.io/micronaut-maven-plugin/latest/

2022-11-18 10:35 UTC, closed without merging

2022-11-18 10:37 UTC, graemerocher commented
how is this closed by the Maven plugin?