3.9.x
micronaut-projects/micronaut-security pull request #1159
Opened 2022-11-28 22:55 UTC by yoeluk

add kid to the jwt header

2022-11-28 22:56 UTC, yoeluk commented
Closes #1150

2022-12-01 16:04 UTC, sdelamo requested changes
Thanks for the PR. Could you add a test?

2022-12-01 16:04 UTC, sdelamo commented on security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/ec/ECSignatureGenerator.java
> +    public Optional<String> getKid() {
annotate the return type as `@NonNull`. Add `@since` to the Javadoc

2022-12-07 14:42 UTC, sdelamo approved these changes

2022-12-07 14:58 UTC, yoeluk commented
@sdelamo yeah sure, I am okay with that. while I was looking at it I draw the conclusion that the current behaviour, when we don't set the kid, of the underlying library (Jose) will set the kid id as `null` so that for consistence and compile-time performance, the `null` was best than optional but otherwise it is fine with me to us an optional too.
For reference this is the build() implementation on the JWSHeader.Builder

```
public JWSHeader build() {

	return new JWSHeader(
		alg, typ, cty, crit,
		jku, jwk, x5u, x5t, x5t256, x5c, kid, b64,
		customParams, parsedBase64URL);
}
```
so if the kid isn't set it will be null anyways.

2022-12-07 15:18 UTC, sdelamo commented
> @sdelamo yeah sure, I am okay with that. while I was looking at it I drew the conclusion that the current behaviour, when we don't set the kid, of the underlying library (Jose) will set the kid id as `null` so that for consistency and compile-time performance, the `null` was best than optional, but otherwise it is fine with me to us an optional too. For reference, this is the build() implementation on the JWSHeader.Builder
> 
> ```
> public JWSHeader build() {
> 
> 	return new JWSHeader(
> 		alg, typ, cty, crit,
> 		jku, jwk, x5u, x5t, x5t256, x5c, kid, b64,
> 		customParams, parsedBase64URL);
> }
> ```
> 
> so if the kid isn't set it will be null anyways.

Yup, we are still passing null or a `kid` to the Nimbus Jose Header builder.  However, for our API I think an `@NonNull Optional<String>` is better than a `@Nullable String getKid()`. But a small detail of course.

2022-12-07 15:20 UTC, merged