Use Micronaut HTTP client for remote JWK Set validation
micronaut-projects/micronaut-security pull request #1509
Opened 2023-11-29 03:09 UTC by jeremyg484

- Initial draft of working implementation.
- Retain existing interface method.

2023-11-29 16:12 UTC, sdelamo requested changes
It is going in the right direction. 

However,  We cannot have breaking changes. Moreover, I think it would to have a `JwksClient` API where we can encapsulate the whole `HttpClient` instantiation etc.  

We could do a `@EachBean(JwksSignatureConfiguration.class`) and create a `JwksClient` bean. 

It needs test.

2023-11-29 16:12 UTC, sdelamo commented on security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwkSetFetcher.java
>      Optional<T> fetch(@Nullable String url);
should this be deprecated?

2023-11-29 16:12 UTC, sdelamo commented on security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignature.java
> -    protected JWKSet loadJwkSet(String url) {
this is a breaking change

2023-11-29 16:12 UTC, sdelamo commented on security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignatureConfiguration.java
> +    String getName();
Extend from the `Named` interface instead.

2023-11-29 16:12 UTC, sdelamo commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
> -    protected JwksSignature jwksSignatureForOpenIdProviderMetadata(@NonNull OpenIdProviderMetadata openIdProviderMetadata) {
this is a breaking change.

2023-12-02 15:38 UTC, jeremyg484 commented
With the latest changes I have:

- Completed refactoring to retain (and deprecate) the existing API methods in favor of the new ones that support propagation of the provider name. The existing methods will still function by passing `null` for the provider name in which case they use the default HTTP client.

- Made the http client a compile only dependency and provided two implementations of a new JwksClient interface - one that uses the Nimbus library's `ResourceRetriever` API that was being used here before, and one that uses the Micronaut `HttpClient`. The `HttpClient` implementation takes precedent if the `HttpClient` is on the class path. This might be overkill, but I think it's the best way to ensure that existing apps don't break.

- Added a set of tests that simulate usage with a proxy for both implementations of JwksClient and ensures that the configured `HttpClient` settings get used. The non-proxy default settings use case is already thoroughly covered with the existing tests.

Some remaining TODOs:

- Figured out why the Java 21 CI build is failing
- Check the AOT optimizations and modify as necessary
- Add some examples to the docs about configuring the `HttpClient` settings for JWK Set retrieval.

2023-12-04 21:02 UTC, jeremyg484 commented
@sdelamo Ready for review now. Note that in this final set of changes that I've moved away from deprecating methods in `DefaultOpenIdTokenResponseValidator` (see my prior comments) and instead added a non-serialized name property to `DefaultOpenIdProviderMetadata`. This approach simplified the changes that had to be made to the AOT optimizations.

2023-12-06 16:43 UTC, merged