major: Move processors to separate module (WIP)
micronaut-projects/micronaut-security pull request #1611
Opened 2024-02-23 14:26 UTC by timyates

Relates to #1588

2024-02-26 11:03 UTC, timyates commented
The coverage is because these are annotation processors, so we have tests that they work, but I don't believe they work during the phase that sonar is watching for coverage

2024-02-26 16:21 UTC, sdelamo requested changes

2024-02-26 16:21 UTC, sdelamo commented on security-oauth2/build.gradle.kts
> +    testImplementation(projects.micronautSecurityProcessor)
should this be `testCompileOnly` for Groovy?

2024-02-26 16:21 UTC, sdelamo commented on security/build.gradle.kts
> +    testImplementation(projects.micronautSecurityProcessor)
```suggestion
    testCompileOnly(projects.micronautSecurityProcessor)
```

2024-02-26 16:21 UTC, sdelamo commented on security-oauth2/build.gradle.kts
> +    testImplementation(projects.micronautSecurityProcessor)
```suggestion
    testCompileOnly(projects.micronautSecurityProcessor)
```

2024-02-27 11:25 UTC, sdelamo approved these changes

2024-02-27 11:26 UTC, sdelamo approved these changes

2024-02-27 11:27 UTC, merged