Remove NonNull annotation of refreshToken parameter
micronaut-projects/micronaut-security pull request #412
Opened 2020-10-09 11:08 UTC by morki

I think it is not valid, because refreshToken parameter can be `null` if `RefreshTokenValidator` and `RefreshTokenPersistence` beans are not provided.

Now it is hard to extend and override those methods, because in Kotlin it results in non-nullable type and invalid checking agains `null` value.

2020-10-27 14:15 UTC, sdelamo commented
@morki can you change your PR to use `@Nullable` instead of removing `@NonNull`?

2020-10-27 15:31 UTC, sdelamo requested changes

2020-10-27 15:31 UTC, sdelamo commented on security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/DefaultAccessRefreshTokenGenerator.java
> +    public Optional<AccessRefreshToken> generate(String refreshToken, @NonNull UserDetails userDetails) {
can you add @Nullable here as well ?

2020-10-27 16:25 UTC, morki commented on security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/DefaultAccessRefreshTokenGenerator.java
> +    public Optional<AccessRefreshToken> generate(String refreshToken, @NonNull UserDetails userDetails) {
Of course, sorry I has overlooked it.

2020-10-28 14:19 UTC, sdelamo approved these changes

2020-10-28 14:19 UTC, merged