Feat: Support for explicitly typed attributes in Authentication (#308)
micronaut-projects/micronaut-security pull request #724
Opened 2021-07-14 21:50 UTC by logineimer

Adds support for explicitly typed attributes in Authentication like @p1729 suggested.

2021-08-11 05:54 UTC, sdelamo requested changes

2021-08-11 05:54 UTC, sdelamo commented on security/src/main/java/io/micronaut/security/authentication/Authentication.java
> +    default <T> Optional<T> getAttribute(String name, @NonNull Class<T> clazz) {
Could you annotate the return type with `@NonNull`

Could you annotate the parameter `name` with `@NonNull`

2021-08-11 05:57 UTC, sdelamo commented
Thanks for the contribution. 

However, I am not sure if we should add this method. I think the recommended way do conversion is to use the [ConversionService](https://docs.micronaut.io/latest/api/index.html).

2021-08-18 21:34 UTC, sdelamo commented
@jameskleeh thoughts ?

2021-08-19 00:17 UTC, jameskleeh commented
The issue with this is that authentication objects are created outside the context and we would need a conversion service instance to do the conversion. There is ConversionService.SHARED we could use but it wouldn't include any converters added via beans, so less than ideal.

2021-08-20 09:07 UTC, sdelamo commented
I am going to close it. My recommendation is for the user to inject `ConversionService` in their singleton or bean where they are querying the authentication. I don't want to add a method to `Authentication`which does not represent best practice.

2021-08-20 09:07 UTC, closed without merging