Add jakarta security annotation mapping
micronaut-projects/micronaut-security pull request #775
Opened 2021-09-10 17:35 UTC by frehov

Switched over the AnnotationMappers for javax security annotations to NamedAnnotationMapper as discussed in #774.
Added the Jakarta equaivalent mappers by extending the javax ones and overriding the namespace.

closes #774

2021-09-10 17:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-security?pullRequest=775) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-security?pullRequest=775) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-security?pullRequest=775) it.</sub>

2021-09-13 11:07 UTC, graemerocher commented
Thanks code changes look good, we will need a test though. Probably just the same as https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/test/groovy/io/micronaut/security/rolesallowed/RolesAllowedSpec.groovy with different annotations

2021-09-13 11:34 UTC, frehov commented
@graemerocher I've extended the original specs and replaced the controllers so that they use the jakarta annotation.
Did a quick debug run of one of the tests, and it did halt in the jakarata annotated controller.

2021-09-14 08:30 UTC, sdelamo requested changes
Please add the annotations to the documentation as well. See `secured.adoc`

2021-09-14 08:30 UTC, sdelamo commented on security-annotations/src/main/java/io/micronaut/security/annotation/JakartaDenyAllAnnotationMapper.java
> +package io.micronaut.security.annotation;
It misses the license

2021-09-14 08:30 UTC, sdelamo commented on security-annotations/src/main/java/io/micronaut/security/annotation/JakartaPermitAllAnnotationMapper.java
> +package io.micronaut.security.annotation;
it misses the license

2021-09-14 08:30 UTC, sdelamo commented on security-annotations/src/main/java/io/micronaut/security/annotation/JakartaRolesAllowedAnnotationMapper.java
> +package io.micronaut.security.annotation;
it misses the license

2021-09-15 08:36 UTC, frehov commented on security-annotations/src/main/java/io/micronaut/security/annotation/JakartaDenyAllAnnotationMapper.java
> +package io.micronaut.security.annotation;
added

2021-09-15 08:36 UTC, frehov commented on security-annotations/src/main/java/io/micronaut/security/annotation/JakartaPermitAllAnnotationMapper.java
> +package io.micronaut.security.annotation;
added

2021-09-15 08:36 UTC, frehov commented on security-annotations/src/main/java/io/micronaut/security/annotation/JakartaRolesAllowedAnnotationMapper.java
> +package io.micronaut.security.annotation;
added

2021-09-15 09:20 UTC, graemerocher approved these changes

2021-09-17 14:54 UTC, sdelamo approved these changes

2021-09-17 14:55 UTC, merged

2021-09-20 07:02 UTC, graemerocher commented
@frehov Thanks for the contribution!