Use new JsonMapper abstraction for serde compatibility
micronaut-projects/micronaut-security pull request #889
Opened 2022-01-04 15:47 UTC by yawkat

FYI: this is still blocked by a bug in the annotation processor, @graemerocher will fix that and we can merge this once a new snapshot is out

2022-01-05 05:04 UTC, sdelamo requested changes
This fails with: 

```
% ./gradlew -x dependencyUpdates check --parallel --continue

> Task :security:compileJava
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
/Users/sdelamo/github/micronaut-projects/micronaut-security/security/src/main/java/io/micronaut/security/authentication/ServerAuthentication.java:37: error: Type to deserialize as [io.micronaut.security.authentication.ClientAuthentication], must be a subtype of the annotated type: io.micronaut.security.authentication.ServerAuthentication
public class ServerAuthentication implements Authentication {
```

2022-01-05 05:04 UTC, sdelamo commented on security-oauth2/build.gradle
> +    mavenCentral()
`mavenCentral` is not necessary. I think that It is added as a repository by `io.micronaut.build.internal.module`

2022-01-05 05:04 UTC, sdelamo commented on security/build.gradle
> +    mavenCentral()
`mavenCentral` is not necessary. I think that It is added as a repository by `io.micronaut.build.internal.module`

2022-01-05 05:05 UTC, sdelamo commented on security-oauth2/build.gradle
> +    annotationProcessor "io.micronaut.serde:micronaut-serde-processor:1.0.0-SNAPSHOT"
I've done this change.

2022-01-05 05:05 UTC, sdelamo commented on security/build.gradle
> +    annotationProcessor "io.micronaut.serde:micronaut-serde-processor:1.0.0-SNAPSHOT"
I've done this change.

2022-01-05 05:06 UTC, sdelamo commented on security-oauth2/build.gradle
> +    mavenCentral()
I've done this change.

2022-01-05 05:06 UTC, sdelamo commented on security/build.gradle
> +    mavenCentral()
I've done this change.

2022-01-05 08:50 UTC, yawkat commented on security-oauth2/src/main/java/io/micronaut/security/oauth2/client/OpenIdClientFactory.java
> -    OpenIdClientFactory(BeanContext beanContext, ObjectMapper objectMapper) {
the constructor is package-private, should be fine like this

2022-01-05 08:50 UTC, yawkat commented
> This fails with:
> 
> ```
> % ./gradlew -x dependencyUpdates check --parallel --continue
> 
> > Task :security:compileJava
> warning: unknown enum constant When.MAYBE
>   reason: class file for javax.annotation.meta.When not found
> /Users/sdelamo/github/micronaut-projects/micronaut-security/security/src/main/java/io/micronaut/security/authentication/ServerAuthentication.java:37: error: Type to deserialize as [io.micronaut.security.authentication.ClientAuthentication], must be a subtype of the annotated type: io.micronaut.security.authentication.ServerAuthentication
> public class ServerAuthentication implements Authentication {
> ```

@graemerocher looks like a bug?

2022-01-11 11:52 UTC, sdelamo commented
@yawkat any feedback about this?

2022-01-11 13:04 UTC, graemerocher commented
@sdelamo the error should be fixed in the latest snapshot

2022-01-11 14:10 UTC, yawkat commented
the error is different now: https://ge.micronaut.io/s/5gde4hmsyj374/failure#1 – missing dependency in serde?

2022-01-14 11:23 UTC, yawkat commented
ok the build is fixed, but there is one more issue: In `KeysController` ( https://github.com/micronaut-projects/micronaut-security/blob/3f593f79b78673e203a083129795d7467b0f655f/security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/KeysController.java#L67 ), when there are no keys, a map `["keys":[]]` is serialized. For JWKS, this *must* be serialized as `{"keys":[]}`. However with our default jackson settings, this can only work if we call `setSerializationInclusion(JsonInclude.Include.ALWAYS)` on the `ObjectMapper`. This setting can't be accessed with the implementation-independent `JsonMapper` API.

@graemerocher any idea? The best I can think up is transforming the `Map` to a `JsonNode`, which is not subject to serialization inclusion settings, but that'd be quite convoluted.

2022-01-14 11:47 UTC, graemerocher commented
perhaps this method needs implementing for serde:

```
    @Override
    default JsonMapper cloneWithFeatures(JsonFeatures features) {
        return this;
    }
```

2022-01-14 12:57 UTC, yawkat commented
JsonFeatures has no common API atm, it's basically a placeholder object to store the information of `@JacksonFeatures`

2022-01-14 13:05 UTC, graemerocher commented
Right, a common API would need to be added to check if inclusion is enabled

2022-01-17 10:27 UTC, yawkat commented
ive added a workaround

2022-01-17 14:18 UTC, merged